<#
.SYNOPSIS
    Regenerates src/cultureNames.ts from .NET.

.DESCRIPTION
    Two things here are not obvious:

    1. GetCultures() alone is not enough. On ICU it omits zh-TW, pa-IN,
       ca-ES-valencia and more, so a list built from it stops recognising
       Resources.zh-TW.resx.
    2. The LCID sweep recovers them, because the runtime's LCID -> name table
       does not vary by backend. It reads each culture's Name; no number ever
       enters the list. LCID 4096 is what an unknown tag like zz gets, which is
       why constructing a CultureInfo cannot validate anything.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$names = [System.Collections.Generic.HashSet[string]]::new()

$isoTypes = [System.Globalization.CultureTypes]::NeutralCultures -bor [System.Globalization.CultureTypes]::SpecificCultures

foreach ($culture in [System.Globalization.CultureInfo]::GetCultures($isoTypes)) {
    if ($culture.Name -ne "") {
        [void]$names.Add($culture.Name.ToLowerInvariant())
    }
}

$enumerated = $names.Count

# Unassigned LCIDs throw and are skipped. The ceiling has to clear the legacy
# alias range at 0x7C00 - zh-CHT is 0x7C04 - so it is 0xFFFF, not 0x5FFF.
for ($lcid = 1; $lcid -le 0xFFFF; $lcid++) {
    try {
        $culture = [System.Globalization.CultureInfo]::GetCultureInfo($lcid)
        if ($culture.LCID -ne 4096 -and $culture.Name -ne "") {
            [void]$names.Add($culture.Name.ToLowerInvariant())
        }
    }
    catch {
        # Not an assigned LCID.
    }
}

foreach ($pseudo in @("qps-ploc", "qps-ploca", "qps-plocm", "qps-latn-x-sh")) {
    [void]$names.Add($pseudo)
}

<#
    Names the LCID sweep brings back that are superseded rather than merely
    unenumerated, each dropped in favour of the spelling beside it - which the
    sweep or the enumeration supplies, so nothing is lost but the old name.

    Nothing else the sweep finds is deprecated. `zh-TW`, `pa-IN` and `ur-PK`
    are current and ISO spelled; ICU only canonicalizes them to `zh-Hant-TW`
    and friends, which is why enumerating alone misses them.
#>
$deprecated = @{
    "zh-chs"     = "zh-hans"      # Deprecated by Microsoft in .NET 2.0.
    "zh-cht"     = "zh-hant"      # Deprecated by Microsoft in .NET 2.0.
    "sr-cyrl-cs" = "sr-cyrl-rs"   # CS was Serbia and Montenegro, dissolved in 2006.
    "sr-latn-cs" = "sr-latn-rs"   # CS was Serbia and Montenegro, dissolved in 2006.
    "quz"        = "qu"           # Legacy Windows spelling of Quechua.
    "quz-bo"     = "qu-bo"
    "quz-ec"     = "qu-ec"
    "quz-pe"     = "qu-pe"
}

foreach ($old in $deprecated.Keys) {
    $replacement = $deprecated[$old]
    if ($names.Contains($replacement) -eq $false) {
        throw "Refusing to drop '$old': its replacement '$replacement' is not in the list."
    }

    [void]$names.Remove($old)
}

$sorted = [string[]]($names | Sort-Object -CaseSensitive)
Write-Host "$enumerated cultures enumerated, $($sorted.Length) after the LCID sweep, pseudo-locales and dropping $($deprecated.Count) deprecated names."

$lines = [System.Collections.Generic.List[string]]::new()
$current = "   "
foreach ($name in $sorted) {
    $quoted = " `"$name`","
    if ($current.Length + $quoted.Length -gt 100) {
        $lines.Add($current)
        $current = "   "
    }

    $current += $quoted
}

$lines.Add($current.TrimEnd(","))

$prefix = @'
/*
 * Generated by scripts/generateCultureNames.ps1 - our list of what counts as a
 * culture in a resx file name, folded. Sourced from .NET, then curated: eight
 * superseded spellings dropped, pseudo-locales added. Nothing reads .NET at
 * runtime. Adding one by hand is fine - lowercase, sorted, canonical BCP-47,
 * and nothing that is also a file name fragment.
 */
const names = new Set<string>([
'@

$suffix = @'
]);

/**
 * The culture names a resx file can be named for - membership is the whole test,
 * so `Resources.bak.resx` is a resource, not a "bak" translation. .NET cannot
 * answer this at runtime: `new CultureInfo("zz")` succeeds. MSBuild decides it
 * the same way, which keeps our translations and the build's satellite
 * assemblies the same set of files.
 */
export class CultureNames {
    /** Folded, like ResxFileName.cultureKey: `fr-CA` and `fr-ca` are one culture. */
    public static has(culture: string): boolean {
        return names.has(culture.toLowerCase());
    }

    /** Only so a test can catch a generated file that came out empty. */
    public static get count(): number {
        return names.size;
    }
}
'@

$target = Join-Path $PSScriptRoot ".." "src" "cultureNames.ts"
$content = $prefix + "`n" + ($lines -join "`n") + "`n" + $suffix
[System.IO.File]::WriteAllText($target, $content.Replace("`r`n", "`n"))
Write-Host "Wrote $(Resolve-Path $target)"
