/*
 * Generated by scripts/generateCultureNames.ps1 - our list of what counts as a
 * culture in a resx file name, folded. Sourced from .NET, then curated: eight
 * superseded spellings dropped, pseudo-locales added. Nothing reads .NET at
 * runtime. Adding one by hand is fine - lowercase, sorted, canonical BCP-47,
 * and nothing that is also a file name fragment.
 */
const names = new Set<string>([
    "af", "af-na", "af-za", "agq", "agq-cm", "ain", "ain-jp", "ak", "ak-gh", "am", "am-et", "apw",
    "apw-us", "ar", "ar-001", "ar-ae", "ar-bh", "ar-dj", "ar-dz", "ar-eg", "ar-eh", "ar-er",
    "ar-il", "ar-iq", "ar-jo", "ar-km", "ar-kw", "ar-lb", "ar-ly", "ar-ma", "ar-mr", "ar-om",
    "ar-ps", "ar-qa", "ar-sa", "ar-sd", "ar-so", "ar-ss", "ar-sy", "ar-td", "ar-tn", "ar-ye", "arn",
    "arn-cl", "as", "as-in", "asa", "asa-tz", "ast", "ast-es", "az", "az-cyrl", "az-cyrl-az",
    "az-latn", "az-latn-az", "ba", "ba-ru", "bas", "bas-cm", "be", "be-by", "bem", "bem-zm", "ber",
    "ber-latn", "ber-latn-ma", "ber-tfng", "ber-tfng-ma", "bez", "bez-tz", "bg", "bg-bg", "bgc",
    "bgc-in", "bho", "bho-in", "bin", "bin-ng", "blo", "blo-bj", "bm", "bm-ml", "bn", "bn-bd",
    "bn-in", "bo", "bo-cn", "bo-in", "br", "br-fr", "brx", "brx-in", "bs", "bs-cyrl", "bs-cyrl-ba",
    "bs-latn", "bs-latn-ba", "byn", "byn-er", "ca", "ca-ad", "ca-es", "ca-es-valencia", "ca-fr",
    "ca-it", "ccp", "ccp-bd", "ccp-in", "ce", "ce-ru", "ceb", "ceb-ph", "cgg", "cgg-ug", "cho",
    "cho-us", "chr", "chr-cher", "chr-cher-us", "chr-us", "cic", "cic-us", "ckb", "ckb-iq",
    "ckb-ir", "co", "co-fr", "cs", "cs-cz", "csw", "csw-ca", "cv", "cv-ru", "cy", "cy-gb", "da",
    "da-dk", "da-gl", "dav", "dav-ke", "de", "de-at", "de-be", "de-ch", "de-de", "de-it", "de-li",
    "de-lu", "dje", "dje-ne", "doi", "doi-in", "dsb", "dsb-de", "dua", "dua-cm", "dv", "dv-mv",
    "dyo", "dyo-sn", "dz", "dz-bt", "ebu", "ebu-ke", "ee", "ee-gh", "ee-tg", "el", "el-cy", "el-gr",
    "en", "en-001", "en-029", "en-150", "en-ae", "en-ag", "en-ai", "en-al", "en-ar", "en-as",
    "en-at", "en-au", "en-bb", "en-bd", "en-be", "en-bg", "en-bi", "en-bm", "en-bn", "en-br",
    "en-bs", "en-bw", "en-bz", "en-ca", "en-cc", "en-ch", "en-ck", "en-cl", "en-cm", "en-cn",
    "en-co", "en-cv", "en-cx", "en-cy", "en-cz", "en-de", "en-dg", "en-dk", "en-dm", "en-ee",
    "en-er", "en-fi", "en-fj", "en-fk", "en-fm", "en-fr", "en-gb", "en-gd", "en-gg", "en-gh",
    "en-gi", "en-gm", "en-gr", "en-gu", "en-gy", "en-hk", "en-hu", "en-id", "en-ie", "en-il",
    "en-im", "en-in", "en-io", "en-je", "en-jm", "en-jp", "en-ke", "en-ki", "en-kn", "en-kr",
    "en-ky", "en-lc", "en-lr", "en-ls", "en-lt", "en-lv", "en-mg", "en-mh", "en-mm", "en-mo",
    "en-mp", "en-ms", "en-mt", "en-mu", "en-mv", "en-mw", "en-mx", "en-my", "en-na", "en-nf",
    "en-ng", "en-nl", "en-no", "en-nr", "en-nu", "en-nz", "en-pg", "en-ph", "en-pk", "en-pl",
    "en-pn", "en-pr", "en-pt", "en-pw", "en-ru", "en-rw", "en-sa", "en-sb", "en-sc", "en-sd",
    "en-se", "en-sg", "en-sh", "en-si", "en-sk", "en-sl", "en-ss", "en-sx", "en-sz", "en-tc",
    "en-th", "en-tk", "en-to", "en-tr", "en-tt", "en-tv", "en-tw", "en-tz", "en-ua", "en-ug",
    "en-um", "en-us", "en-us-posix", "en-vc", "en-vg", "en-vi", "en-vu", "en-ws", "en-za", "en-zm",
    "en-zw", "eo", "eo-001", "es", "es-003", "es-419", "es-ag", "es-ar", "es-bb", "es-bm", "es-bo",
    "es-bq", "es-br", "es-bs", "es-bz", "es-ca", "es-cl", "es-co", "es-cr", "es-cu", "es-cw",
    "es-dm", "es-do", "es-ea", "es-ec", "es-es", "es-gd", "es-gq", "es-gt", "es-gy", "es-hn",
    "es-ht", "es-ic", "es-kn", "es-ky", "es-lc", "es-mx", "es-ni", "es-pa", "es-pe", "es-ph",
    "es-pr", "es-py", "es-sv", "es-tc", "es-tt", "es-us", "es-uy", "es-vc", "es-ve", "es-vg",
    "es-vi", "et", "et-ee", "eu", "eu-es", "ewo", "ewo-cm", "fa", "fa-af", "fa-ir", "ff", "ff-adlm",
    "ff-adlm-bf", "ff-adlm-cm", "ff-adlm-gh", "ff-adlm-gm", "ff-adlm-gn", "ff-adlm-gw",
    "ff-adlm-lr", "ff-adlm-mr", "ff-adlm-ne", "ff-adlm-ng", "ff-adlm-sl", "ff-adlm-sn", "ff-latn",
    "ff-latn-bf", "ff-latn-cm", "ff-latn-gh", "ff-latn-gm", "ff-latn-gn", "ff-latn-gw",
    "ff-latn-lr", "ff-latn-mr", "ff-latn-ne", "ff-latn-ng", "ff-latn-sl", "ff-latn-sn", "ff-ng",
    "fi", "fi-fi", "fil", "fil-ph", "fo", "fo-dk", "fo-fo", "fr", "fr-029", "fr-be", "fr-bf",
    "fr-bi", "fr-bj", "fr-bl", "fr-ca", "fr-cd", "fr-cf", "fr-cg", "fr-ch", "fr-ci", "fr-cm",
    "fr-dj", "fr-dz", "fr-fr", "fr-ga", "fr-gf", "fr-gn", "fr-gp", "fr-gq", "fr-ht", "fr-km",
    "fr-lu", "fr-ma", "fr-mc", "fr-mf", "fr-mg", "fr-ml", "fr-mq", "fr-mr", "fr-mu", "fr-nc",
    "fr-ne", "fr-pf", "fr-pm", "fr-re", "fr-rw", "fr-sc", "fr-sn", "fr-sy", "fr-td", "fr-tg",
    "fr-tn", "fr-vu", "fr-wf", "fr-yt", "fur", "fur-it", "fy", "fy-nl", "ga", "ga-gb", "ga-ie",
    "gaa", "gaa-gh", "gd", "gd-gb", "gez", "gez-er", "gez-et", "gl", "gl-es", "gn", "gn-py", "gsw",
    "gsw-ch", "gsw-fr", "gsw-li", "gu", "gu-in", "guz", "guz-ke", "gv", "gv-im", "ha", "ha-gh",
    "ha-latn", "ha-latn-ng", "ha-ne", "ha-ng", "haw", "haw-us", "he", "he-il", "hi", "hi-in",
    "hi-latn", "hi-latn-in", "hmn", "hmn-cn", "hr", "hr-ba", "hr-hr", "hsb", "hsb-de", "hu",
    "hu-hu", "hy", "hy-am", "ia", "ia-001", "ibb", "ibb-ng", "id", "id-id", "ie", "ie-ee", "ig",
    "ig-ng", "ii", "ii-cn", "inh", "io", "io-001", "is", "is-is", "it", "it-ch", "it-it", "it-sm",
    "it-va", "iu", "iu-ca", "iu-cans", "iu-cans-ca", "iu-latn", "iu-latn-ca", "ja", "ja-jp", "jbo",
    "jbo-001", "jgo", "jgo-cm", "jmc", "jmc-tz", "jv", "jv-id", "ka", "ka-ge", "kab", "kab-dz",
    "kaj", "kaj-ng", "kam", "kam-ke", "kcg", "kcg-ng", "kde", "kde-tz", "kea", "kea-cv", "kgp",
    "kgp-br", "khq", "khq-ml", "ki", "ki-ke", "kk", "kk-cyrl", "kk-cyrl-kz", "kk-kz", "kkj",
    "kkj-cm", "kl", "kl-gl", "kln", "kln-ke", "km", "km-kh", "kn", "kn-in", "ko", "ko-cn", "ko-kp",
    "ko-kr", "kok", "kok-deva", "kok-deva-in", "kok-in", "kok-latn", "kok-latn-in", "kpe", "kpe-gn",
    "kpe-lr", "kr", "kr-ng", "ks", "ks-arab", "ks-arab-in", "ks-aran-in", "ks-deva", "ks-deva-in",
    "ksb", "ksb-tz", "ksf", "ksf-cm", "ksh", "ksh-de", "ku", "ku-arab", "ku-arab-iq", "ku-tr", "kw",
    "kw-gb", "kxv", "kxv-deva", "kxv-deva-in", "kxv-latn", "kxv-latn-in", "kxv-orya", "kxv-orya-in",
    "kxv-telu", "kxv-telu-in", "ky", "ky-kg", "la", "la-001", "lag", "lag-tz", "lb", "lb-lu", "lg",
    "lg-ug", "lij", "lij-it", "lkt", "lkt-us", "lmo", "lmo-it", "ln", "ln-ao", "ln-cd", "ln-cf",
    "ln-cg", "lo", "lo-la", "lrc", "lrc-iq", "lrc-ir", "lt", "lt-lt", "lu", "lu-cd", "luo",
    "luo-ke", "lut", "luy", "luy-ke", "lv", "lv-lv", "mai", "mai-in", "mas", "mas-ke", "mas-tz",
    "mer", "mer-ke", "mfe", "mfe-mu", "mg", "mg-mg", "mgh", "mgh-mz", "mgo", "mgo-cm", "mi",
    "mi-nz", "mic", "mic-ca", "mid", "mid-iq", "mk", "mk-mk", "ml", "ml-in", "mn", "mn-cyrl",
    "mn-mn", "mn-mong", "mn-mong-cn", "mn-mong-mn", "mni", "mni-beng", "mni-beng-in", "mni-in",
    "mni-mtei", "mni-mtei-in", "moh", "moh-ca", "mr", "mr-in", "ms", "ms-arab", "ms-arab-bn",
    "ms-arab-my", "ms-bn", "ms-id", "ms-my", "ms-sg", "mt", "mt-mt", "mua", "mua-cm", "mus",
    "mus-us", "my", "my-mm", "myv", "myv-ru", "mzn", "mzn-ir", "naq", "naq-na", "nb", "nb-no",
    "nb-sj", "nd", "nd-zw", "nds", "nds-de", "nds-nl", "ne", "ne-in", "ne-np", "nl", "nl-aw",
    "nl-be", "nl-bq", "nl-cw", "nl-nl", "nl-sr", "nl-sx", "nmg", "nmg-cm", "nn", "nn-no", "nnh",
    "nnh-cm", "nnp", "nnp-in", "no", "nqo", "nqo-gn", "nr", "nr-za", "nso", "nso-za", "nus",
    "nus-ss", "nv", "nv-us", "ny", "ny-mw", "nyn", "nyn-ug", "oc", "oc-es", "oc-fr", "om", "om-et",
    "om-ke", "or", "or-in", "os", "os-ge", "os-ru", "osa", "osa-us", "pa", "pa-arab", "pa-arab-pk",
    "pa-aran-pk", "pa-guru", "pa-guru-in", "pa-in", "pap", "pap-029", "pcm", "pcm-ng", "pl",
    "pl-pl", "pqm", "pqm-ca", "prg", "prg-pl", "prs", "prs-af", "ps", "ps-af", "ps-pk", "pt",
    "pt-ao", "pt-br", "pt-ch", "pt-cv", "pt-fr", "pt-gq", "pt-gw", "pt-lu", "pt-mo", "pt-mz",
    "pt-pt", "pt-st", "pt-tl", "qps-latn-x-sh", "qps-ploc", "qps-ploca", "qps-plocm", "qu", "qu-bo",
    "qu-ec", "qu-pe", "quc", "quc-latn", "quc-latn-gt", "raj", "raj-in", "rej", "rej-id",
    "rej-rjng", "rej-rjng-id", "rhg", "rhg-rohg", "rhg-rohg-bd", "rhg-rohg-mm", "rm", "rm-ch", "rn",
    "rn-bi", "ro", "ro-md", "ro-ro", "rof", "rof-tz", "ru", "ru-by", "ru-kg", "ru-kz", "ru-md",
    "ru-ru", "ru-ua", "rw", "rw-rw", "rwk", "rwk-tz", "sa", "sa-in", "sah", "sah-ru", "saq",
    "saq-ke", "sat", "sat-deva", "sat-deva-in", "sat-olck", "sat-olck-in", "sbp", "sbp-tz", "sc",
    "sc-it", "scn", "scn-it", "sd", "sd-arab", "sd-arab-pk", "sd-deva", "sd-deva-in", "se", "se-fi",
    "se-no", "se-se", "seh", "seh-mz", "ses", "ses-ml", "sg", "sg-cf", "shi", "shi-latn",
    "shi-latn-ma", "shi-tfng", "shi-tfng-ma", "si", "si-lk", "sjd", "sje", "sju", "sk", "sk-sk",
    "sl", "sl-si", "sm", "sm-as", "sm-ws", "sma", "sma-no", "sma-se", "smj", "smj-no", "smj-se",
    "smn", "smn-fi", "sms", "sms-fi", "sn", "sn-zw", "so", "so-dj", "so-et", "so-ke", "so-so", "sq",
    "sq-al", "sq-mk", "sq-xk", "sr", "sr-cyrl", "sr-cyrl-ba", "sr-cyrl-me", "sr-cyrl-rs",
    "sr-cyrl-xk", "sr-latn", "sr-latn-ba", "sr-latn-me", "sr-latn-rs", "sr-latn-xk", "ss", "ss-sz",
    "ss-za", "st", "st-ls", "st-za", "su", "su-latn", "su-latn-id", "sv", "sv-ax", "sv-fi", "sv-se",
    "sw", "sw-cd", "sw-ke", "sw-tz", "sw-ug", "syr", "syr-iq", "syr-sy", "szl", "szl-pl", "ta",
    "ta-in", "ta-lk", "ta-my", "ta-sg", "te", "te-in", "teo", "teo-ke", "teo-ug", "tg", "tg-cyrl",
    "tg-cyrl-tj", "tg-tj", "th", "th-th", "ti", "ti-er", "ti-et", "tig", "tig-er", "tk", "tk-tm",
    "tn", "tn-bw", "tn-za", "to", "to-to", "tok", "tok-001", "tr", "tr-cy", "tr-tr", "trv",
    "trv-tw", "ts", "ts-za", "tt", "tt-ru", "twq", "twq-ne", "tzm", "tzm-arab-ma", "tzm-latn",
    "tzm-latn-dz", "tzm-ma", "tzm-tfng", "tzm-tfng-ma", "ug", "ug-cn", "uk", "uk-ua", "ur",
    "ur-arab", "ur-arab-in", "ur-arab-pk", "ur-aran-in", "ur-aran-pk", "ur-in", "ur-pk", "uz",
    "uz-arab", "uz-arab-af", "uz-cyrl", "uz-cyrl-uz", "uz-latn", "uz-latn-uz", "vai", "vai-latn",
    "vai-latn-lr", "vai-vaii", "vai-vaii-lr", "ve", "ve-za", "vec", "vec-it", "vi", "vi-vn", "vmw",
    "vmw-mz", "vun", "vun-tz", "wa", "wa-be", "wae", "wae-ch", "wal", "wal-et", "wo", "wo-sn", "xh",
    "xh-za", "xnr", "xnr-in", "xog", "xog-ug", "yav", "yav-cm", "yi", "yi-001", "yi-ua", "yo",
    "yo-bj", "yo-ng", "yrl", "yrl-br", "yrl-co", "yrl-ve", "yue", "yue-hans", "yue-hans-cn",
    "yue-hant", "yue-hant-cn", "yue-hant-hk", "za", "za-cn", "zgh", "zgh-ma", "zh", "zh-cn",
    "zh-hans", "zh-hans-cn", "zh-hans-hk", "zh-hans-jp", "zh-hans-mo", "zh-hans-my", "zh-hans-sg",
    "zh-hant", "zh-hant-cn", "zh-hant-hk", "zh-hant-jp", "zh-hant-mo", "zh-hant-my", "zh-hant-tw",
    "zh-hk", "zh-mo", "zh-sg", "zh-tw", "zu", "zu-za"
]);

/**
 * The culture names a resx file can be named for - membership is the whole test,
 * so `Resources.bak.resx` is a resource, not a "bak" translation. .NET cannot
 * answer this at runtime: `new CultureInfo("zz")` succeeds. MSBuild decides it
 * the same way, which keeps our translations and the build's satellite
 * assemblies the same set of files.
 */
export class CultureNames {
    /** Folded, like ResxFileName.cultureKey: `fr-CA` and `fr-ca` are one culture. */
    public static has(culture: string): boolean {
        return names.has(culture.toLowerCase());
    }

    /** Only so a test can catch a generated file that came out empty. */
    public static get count(): number {
        return names.size;
    }
}