import * as vscode from "vscode";

import { promises as fsPromises } from "fs";
import { PreviewEditPanel } from "./previewEditPanel";
import * as path from "path";
import *  as xmljs from "xml-js";
import { ResxEditorProvider } from "./resxEditorProvider";
import { NotificationService } from "./notificationService";
import { FileHelper } from "./fileHelper";
import { TextInputBoxOptions } from "./textInputBoxOptions";


let currentContext: vscode.ExtensionContext;
var shouldGenerateStronglyTypedResourceClassOnSave: boolean = false;

export const resxpress = "resxpress";

export function activate(context: vscode.ExtensionContext) {
	try {
		const notificationService = new NotificationService(context);
		notificationService.promptForReviewAsync();
	}
	catch (error) {
		console.error(error);
	}

	currentContext = context;
	loadConfiguration();

	vscode.workspace.onDidChangeConfiguration(loadConfiguration);

	context.subscriptions.push(vscode.commands.registerTextEditorCommand(`${resxpress}.resxpreview`,
		async () => {
			vscode.window.withProgress({
				location: vscode.ProgressLocation.Notification,
				cancellable: false,
				title: "ResXpress",
			},
				async (p) => {
					p.report({ message: "Showing Preview" });
					await displayAsMarkdown();
				}
			);
		}));

	context.subscriptions.push(vscode.commands.registerTextEditorCommand(`${resxpress}.sortbykeys`,
		async () => {
			vscode.window.withProgress({
				location: vscode.ProgressLocation.Notification,
				cancellable: false,
				title: "ResXpress",
			}, async (p) => {
				p.report({ message: "Sorting by keys" });
				await sortByKeys();
			});
		}));

	context.subscriptions.push(vscode.commands.registerTextEditorCommand(`${resxpress}.newpreview`,
		async () => {
			vscode.window.withProgress({
				location: vscode.ProgressLocation.Notification,
				cancellable: false,
				title: "ResXpress"
			}, async (progress) => {
				progress.report({ message: "Showing Web Preview" });
				await newPreview();
			});
		}));

	context.subscriptions.push(vscode.commands.registerCommand(`${resxpress}.setNameSpace`, async (uri: vscode.Uri) => await setNamespace(uri)))

	context.subscriptions.push(vscode.commands.registerCommand(`${resxpress}.createResxFile`, async (uri: vscode.Uri) => await createResxFile(uri)))

	context.subscriptions.push(vscode.commands.registerTextEditorCommand(`${resxpress}.resxeditor`, async () => await newPreview()));

	context.subscriptions.push(ResxEditorProvider.register(context));

	vscode.workspace.onDidSaveTextDocument(async (document) => {
		try {
			var isResx = document.fileName.endsWith(".resx");
			if (isResx && shouldGenerateStronglyTypedResourceClassOnSave) {
				await runResGenAsync(document);
			}
		}
		catch (error) {
			var errorMessage = "";
			if (error instanceof Error) {
				errorMessage = error.message;
			}
			else if (typeof error === "string") {
				errorMessage = error;
			}
			console.error(error);
			vscode.window.showErrorMessage(errorMessage);
		}
	});

	console.log(`Extension ${context.extension.id} activated`);
}

function loadConfiguration() {
	let resxConfig = vscode.workspace.getConfiguration("resxpress.configuration");
	shouldGenerateStronglyTypedResourceClassOnSave = resxConfig.get<boolean>("generateStronglyTypedResourceClassOnSave") ?? false;
}

function startsWithNumber(str: string): boolean {
	if (str.length === 0) {
		return false;
	}

	const firstChar = str[0];

	// Check if the first character is a digit
	if (!isNaN(Number(firstChar))) {
		return true;
	}
	return false;
}

function convertToPascalCase(str: string): string {
	// Add an underscore before the first numeric character
	const modifiedStr = str.replace(/^(\d+)/, "_$1");
	// Remove invalid characters and replace spaces with underscores
	const cleanedStr = modifiedStr.replace(/[^a-zA-Z0-9_]/g, "").replace(/\s+/g, "_");

	// Split the string into words
	const words = cleanedStr.split("_");

	// Convert each word to PascalCase and concatenate
	return words.map(word => {
		return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
	}).join("");
}


export async function runResGenAsync(document: vscode.TextDocument): Promise<void> {
	let filename = FileHelper.getFileNameNoExt(document);
	let csharpFileName = "Resources.cs";
	if (filename !== null) {
		csharpFileName = `${filename}.Designer.cs`;
	}

	let nameSpace = await FileHelper.tryGetNamespace(document);

	if (nameSpace === null || nameSpace === "") {
		nameSpace = path.basename(path.dirname(filename));
	}


	let documentText = FileHelper.getActiveDocumentText();
	if (documentText != "") {
		var jsObj = xmljs.xml2js(documentText);
		var resourceCSharpClassText = "";
		let accessModifier = "public";
		let workspacePath = FileHelper.getDirectory(document);

		resourceCSharpClassText += `namespace ${nameSpace}
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the Visual Studio Code Extension PrateekMahendrakar.resxpress
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	${accessModifier} class ${filename} 
	{
		private static global::System.Resources.ResourceManager resourceMan;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		${accessModifier} ${filename}()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		${accessModifier} static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("${nameSpace}.${filename}", typeof(${filename}).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		${accessModifier} static global::System.Globalization.CultureInfo Culture { get; set; }`;

		if (jsObj.elements[0].elements.length > 0) {
			jsObj.elements[0].elements.forEach((element: any) => {
				if (element.name === "data") {
					const resourceKey = element.attributes.name;
					let valueElementParent = element.elements.filter((x: any) => x.name === "value")?.[0];
					let value = valueElementParent?.elements?.length > 0 ? valueElementParent.elements[0].text : "";

					var propertyNameReg = resourceKey.replace(/ /g, "_");
					if (propertyNameReg !== null) {
						var propertyName: string = propertyNameReg.toString();
						propertyName = convertToPascalCase(propertyName);
						if (startsWithNumber(propertyName)) {
							propertyName = `_${propertyName}`;
						}
						resourceCSharpClassText += `
	
			/// <summary>
			/// Looks up a localized string similar to ${value}.
			/// </summary>
			${accessModifier} static string ${propertyName} => ResourceManager.GetString("${resourceKey}", Culture);`;
					}
				}
			});
		}
		else {
			resourceCSharpClassText += `
	}`;
		}


		resourceCSharpClassText += `
	}
}`;
		console.log(resourceCSharpClassText);


		if (workspacePath != null) {
			let pathToWrite = path.join(workspacePath, csharpFileName);
			await FileHelper.writeToFile(pathToWrite, resourceCSharpClassText);
		}
	}
}


export function deactivate() {
	console.log(`${resxpress} deactivated`);
}

async function sortByKeys() {
	try {
		let unordered: any = sortKeyValuesResx();

		let editor = vscode.window.activeTextEditor;

		if (editor) {
			let document = editor.document;

			var ranger = new vscode.Range(0, 0, document.lineCount, 0);

			editor.edit((editBuilder) => {
				editBuilder.replace(ranger, unordered);
			});
		}
	}
	catch (error) {
		var errorMessage = "";
		if (error instanceof Error) {
			errorMessage = error.message;
		}
		else if (typeof error === "string") {
			errorMessage = error;
		}
		vscode.window.showErrorMessage(errorMessage);
		console.error(error);
	}
}

function sortKeyValuesResx(reverse?: boolean) {
	try {
		var text = vscode.window.activeTextEditor?.document?.getText() ?? "";
		var jsObj = xmljs.xml2js(text);

		var dataList: any = [];
		var sorted: any = [];
		jsObj.elements[0].elements.forEach((x: any) => {
			if (x.name === "data") {
				dataList.push(x);
			}
			else {
				sorted.push(x);
			}
		});

		var dataListsorted = dataList.sort((x1: any, x2: any) => {
			if (reverse) {
				return x1.attributes.name > x2.attributes.name ? -1 : x1.attributes.name < x2.attributes.name ? 1 : 0;
			} else {
				return x1.attributes.name < x2.attributes.name ? -1 : x1.attributes.name > x2.attributes.name ? 1 : 0;
			}
		});

		sorted.push(...dataListsorted);
		jsObj.elements[0].elements = sorted;

		var xml = xmljs.js2xml(jsObj, { spaces: 4 });

		return xml;
	}
	catch (error) {
		var errorMessage = "";
		if (error instanceof Error) {
			errorMessage = error.message;
		}
		else if (typeof error === "string") {
			errorMessage = error;
		}
		vscode.window.showErrorMessage(errorMessage);
		console.error(error);
	}
}

function getDataJs(): any[] {
	var text = vscode.window.activeTextEditor?.document?.getText() ?? "";
	var jsObj: any = xmljs.xml2js(text, { compact: true });
	return jsObj.root.data;
}

async function newPreview() {
	var text = vscode.window.activeTextEditor?.document?.getText() ?? "";
	var jsObj = xmljs.xml2js(text);
	var dataList: any = [];
	var sorted = [];
	jsObj.elements[0].elements.forEach((x: any) => {
		if (x.name === "data") {
			dataList.push(x);
		}
		else {
			sorted.push(x);
		}
	});

	var currentFileName = vscode.window.activeTextEditor?.document.fileName;
	if (currentFileName) {
		await displayJsonInHtml(dataList, currentFileName);
	}
}


// Markdown Preview
async function displayAsMarkdown() {
	try {
		var pathObj = path.parse(
			vscode.window.activeTextEditor?.document.fileName ?? ""
		);
		if (pathObj) {
			if (pathObj.ext !== ".resx") {
				await vscode.window.showErrorMessage("Not a Resx file.");
				return;
			}
			const jsonData: any[] = getDataJs();
			if (!(jsonData instanceof Error)) {
				var currentFileName = vscode.window.activeTextEditor?.document.fileName;
				if (currentFileName) {
					var fileNameNoExt = vscode.window.activeTextEditor?.document.fileName.substring(
						0,
						currentFileName.lastIndexOf(".")
					);
					let mdFile = fileNameNoExt + ".md";

					let fileContent = `### ${pathObj.name} Preview\n\n| Key | Value | Comment |\n`;
					fileContent += "| --- | --- | --- |" + "\n";

					for (const jsObj of jsonData) {
						const regexM = /[\\`*_{}[\]()#+.!|-]/g;
						//clean up key
						var property = jsObj._attributes.name;
						var propertyString = property;

						propertyString = property.replace(regexM, "\\$&");
						propertyString = property.replace(/\r?\n/g, "<br/>");

						var valueString = jsObj.value?._text;
						var commentString = jsObj.comment?._text ?? "";

						valueString = valueString.replace(regexM, "\\$&");
						valueString = valueString.replace(/\r?\n/g, "<br/>");
						commentString = commentString.replace(regexM, "\\$&");
						commentString = commentString.replace(/\r?\n/g, "<br/>");

						fileContent += `| ${propertyString} | ${valueString} | ${commentString} |\n`;
					}

					await fsPromises.writeFile(mdFile, fileContent);

					let uri = vscode.Uri.file(mdFile);

					await vscode.commands.executeCommand("vscode.open", uri);
					await vscode.commands.executeCommand("markdown.showPreview");
					await vscode.commands.executeCommand("markdown.preview.refresh");
					await vscode.commands.executeCommand("workbench.action.previousEditor");
					await vscode.commands.executeCommand("workbench.action.closeActiveEditor");
				}
			}
			else {
				vscode.window.showErrorMessage("Error parsing resx data");
			}
		}
		else {
			vscode.window.showErrorMessage("Error finding path of the file");
		}
	}
	catch (error) {
		var errorMessage = "";
		if (error instanceof Error) {
			errorMessage = error.message;
		}
		else if (typeof error === "string") {
			errorMessage = error;
		}
		vscode.window.showErrorMessage(errorMessage);
		console.error(error);
	}
}

async function displayJsonInHtml(jsonData: any[], filename: string) {
	try {
		var htmlContent = "";

		jsonData.forEach((element) => {
			var valueStr = "";
			var commentstr = "";
			element.elements.forEach((subElement: any) => {
				if (subElement.name === "value" && subElement.elements?.length > 0) {
					valueStr = subElement.elements[0].text;
				}
				else if (subElement.name === "comment" && subElement.elements?.length > 0) {
					commentstr = subElement.elements[0].text;
				}
			});
			htmlContent += `<tr>
				<td>${element.attributes.name}</td>
				<td>${valueStr}</td>
				<td>${commentstr}</td>
			</tr>`;
		});
		var pathObj = path.parse(filename);
		var title = pathObj.name + pathObj.ext;

		PreviewEditPanel.createOrShow(currentContext.extensionUri, title, htmlContent);
	}
	catch (error) {
		var errorMessage = "";
		if (error instanceof Error) {
			errorMessage = error.message;
		}
		else if (typeof error === "string") {
			errorMessage = error;
		}
		vscode.window.showErrorMessage(errorMessage);
		console.error(error);
	}
}

function isStringRecord(obj: any): obj is Record<string, string> {
	if (obj === null)
		return false;

	if (typeof obj !== "object")
		return false;

	if (Array.isArray(obj))
		return false;

	if (Object.getOwnPropertySymbols(obj).length > 0)
		return false;

	return Object.getOwnPropertyNames(obj).every(p => typeof obj[p] === "string");
}

async function createOrUpdateNamespaceMappingFile(workspaceFolder: vscode.WorkspaceFolder, fileNameNoExt: string, namespace: string) {
	const workspacePath = workspaceFolder.uri.fsPath;
	if (workspacePath) {
		let pathToWrite = path.join(workspacePath, `.${resxpress}/namespace-mapping.json`);
		let content = await FileHelper.getFileText(pathToWrite);
		var didWrite = false;
		if (content.length > 0) {
			let namespaceMaps = JSON.parse(content);
			if (isStringRecord(namespaceMaps)) {
				namespaceMaps[fileNameNoExt] = namespace;
				await FileHelper.writeToFile(pathToWrite, JSON.stringify(namespaceMaps))
				didWrite = true;
			}
		}
		if (didWrite === false) {
			let rec: Record<string, string> = {};
			rec[fileNameNoExt] = namespace;
			await FileHelper.writeToFile(pathToWrite, JSON.stringify(rec))
		}
	}
}

async function setNamespace(uri: vscode.Uri) {
	if (uri) {
		let parsedPath = path.parse(uri.fsPath);
		const fileName = parsedPath.name;
		if (fileName !== null) {
			const inputBoxOptions = new TextInputBoxOptions("Namespace", "", undefined, "Enter namespace", "Namespace", true);
			const namespaceValue = await vscode.window.showInputBox(inputBoxOptions);
			console.log(`namespace entered : ${namespaceValue}`);
			if (namespaceValue) {
				let workspaceFolder = vscode.workspace.getWorkspaceFolder(uri);
				if (workspaceFolder) {
					await createOrUpdateNamespaceMappingFile(workspaceFolder, fileName, namespaceValue);
				}
			} else {
				vscode.window.showErrorMessage("Invalid path for resx file. Cannot set namespace.")
			}
		}
	}
}

async function createResxFile(uri: vscode.Uri | null) {
	// if (uri) {
	// 	console.log(uri.fsPath);
	// }
	const resxFileNameOptions = new TextInputBoxOptions("New Resx File", "", undefined, "Enter Resx file name", ".resx", true);
	let fileName = await vscode.window.showInputBox(resxFileNameOptions);
	if (fileName && fileName.length > 0) {
		if (fileName.endsWith(".resx") === false) {
			fileName = `${fileName}.resx`;
		}
		const newResxFileNamespaceOptions = new TextInputBoxOptions(`namespace for ${fileName}`, "", undefined, `Enter namespace for ${fileName}`, "", true);
		const namespace = await vscode.window.showInputBox(newResxFileNamespaceOptions);
		if (namespace && namespace.length > 0) {
			const workspaceEdit = new vscode.WorkspaceEdit();
			let thisWorkspace = "";
			if (uri) {
				thisWorkspace = uri.toString();
			}
			else if (vscode.workspace.workspaceFolders) {
				thisWorkspace = vscode.workspace.workspaceFolders[0].uri.toString();
			}
			else {
				vscode.window.showErrorMessage("Cannot create resx file!");
				return;
			}
			const resxFilePath = path.join(thisWorkspace, fileName);
			// create a Uri for a file to be created
			const newUri = vscode.Uri.parse(resxFilePath);
			const content = `<?xml version="1.0" encoding="utf-8"?>
<root>
	<resheader name="resmimetype">
		<value>text/microsoft-resx</value>
	</resheader>
	<resheader name="version">
		<value>2.0</value>
	</resheader>
	<resheader name="reader">
		<value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
	</resheader>
	<resheader name="writer">
		<value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
	</resheader>
	<!--Data-->
</root>`;

			let encoder = new TextEncoder();
			let uInt8Array = encoder.encode(content);
			// create an edit that will create a file
			workspaceEdit.createFile(newUri, { ignoreIfExists: true, overwrite: false, contents: uInt8Array });

			//Create file
			await vscode.workspace.applyEdit(workspaceEdit);

			let document = await vscode.workspace.openTextDocument(newUri);
			await vscode.window.showTextDocument(document);
			let workspaceFolder = vscode.workspace.getWorkspaceFolder(newUri);
			
			if (workspaceFolder) {
				const fileNameNoExt = fileName.replace(".resx", "");
				await createOrUpdateNamespaceMappingFile(workspaceFolder, fileNameNoExt, namespace);
			}
			else {
				console.error(`Unable to locate workspaceFolder for ${newUri.fsPath}`)
			}
		}
		else {
			vscode.window.showErrorMessage(`Invalid namespace entered for ${fileName}`);
		}
	}
	else {
		vscode.window.showErrorMessage("Invalid resx file name entered");
	}
}
