# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - master
  pull_request:
      branches:
      - master

name: Publish VS Code Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}