# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - master
  pull_request:
      branches:
      - master
  workflow_dispatch:


- name: GitHub Action for vsce
  uses: lannonbr/vsce-action@2.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.GITHUB_TOKEN }}